-- MySQL Script generated by MySQL Workbench
-- 04/11/21 14:42:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cocobd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cocobd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cocobd` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `cocobd` ;

-- -----------------------------------------------------
-- Table `cocobd`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cocobd`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `precio` FLOAT NOT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocobd`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cocobd`.`usuario` (
  `id_usuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocobd`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cocobd`.`carrito` (
  `cantidad` INT NOT NULL,
  `fecha_compra` DATETIME NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `producto_id_producto` INT NOT NULL,
  INDEX `fk_carrito_usuario1_idx` (`usuario_id_usuario` ASC),
  INDEX `fk_carrito_producto1_idx` (`producto_id_producto` ASC),
  CONSTRAINT `fk_carrito_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `cocobd`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrito_producto1`
    FOREIGN KEY (`producto_id_producto`)
    REFERENCES `cocobd`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocobd`.`descuento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cocobd`.`descuento` (
  `id_descuento` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `porcentaje` DECIMAL NOT NULL,
  `cantidad` DECIMAL NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NOT NULL,
  `producto_id_productos` INT NOT NULL,
  PRIMARY KEY (`id_descuento`),
  INDEX `fk_descuento_producto1_idx` (`producto_id_productos` ASC),
  CONSTRAINT `fk_descuento_producto1`
    FOREIGN KEY (`producto_id_productos`)
    REFERENCES `cocobd`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
